import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { incidentsApi, type Incident } from '../api/client'
import { TypeBadge } from '../components/StatusBadge'
import ReactMarkdown from 'react-markdown'

const TYPE_ICON: Record<string, string> = {
  quick_fix: '🔧',
  edge_case: '🔍',
  architectural: '🏗️',
  unknown: '❓',
}

export default function Postmortems() {
  const [expandedId, setExpandedId] = useState<number | null>(null)

  const { data: incidents = [], isLoading } = useQuery({
    queryKey: ['incidents'],
    queryFn: incidentsApi.list,
  })

  const withPostmortems = incidents.filter((i: Incident) => i.postmortem)

  return (
    <div className="max-w-3xl space-y-6">
      <div>
        <h1 className="text-2xl mb-1" style={{ fontFamily: "'Bitter', serif", fontWeight: 700, color: '#003D4F' }}>
          Post-mortems
        </h1>
        <p className="text-sm" style={{ color: '#003D4F88' }}>
          Incident history and lessons learned, generated by the Autonomic Sentinel.
        </p>
      </div>

      {isLoading ? (
        <div className="space-y-3">
          {[1, 2, 3].map(i => (
            <div key={i} className="h-24 rounded-xl animate-pulse" style={{ backgroundColor: '#FFFFFF' }} />
          ))}
        </div>
      ) : withPostmortems.length === 0 ? (
        <div className="rounded-xl p-12 flex flex-col items-center gap-3 shadow-sm" style={{ backgroundColor: '#FFFFFF' }}>
          <span className="text-4xl">📋</span>
          <p className="font-semibold" style={{ fontFamily: "'Bitter', serif", color: '#003D4F' }}>No post-mortems yet</p>
          <p className="text-sm text-center" style={{ color: '#003D4F66' }}>
            Trigger an incident on the Dashboard, run the agent, then click "Generate Post-mortem".
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {withPostmortems.map((incident: Incident) => {
            const isExpanded = expandedId === incident.id
            return (
              <div key={incident.id} className="rounded-xl shadow-sm overflow-hidden" style={{ backgroundColor: '#FFFFFF' }}>
                {/* Header */}
                <button
                  onClick={() => setExpandedId(isExpanded ? null : incident.id)}
                  className="w-full text-left p-5 flex items-start justify-between gap-4 transition-colors"
                  style={{ backgroundColor: isExpanded ? '#47A1AD0D' : '#FFFFFF' }}
                >
                  <div className="flex items-start gap-3 flex-1 min-w-0">
                    <span className="text-xl shrink-0 mt-0.5">{TYPE_ICON[incident.incident_type] ?? '❓'}</span>
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold truncate" style={{ fontFamily: "'Bitter', serif", color: '#003D4F' }}>
                        {incident.title}
                      </p>
                      <p className="text-xs font-mono mt-0.5 truncate" style={{ color: '#003D4F66' }}>
                        {incident.error_message}
                      </p>
                      <div className="flex items-center gap-3 mt-2">
                        <TypeBadge type={incident.incident_type} />
                        {incident.github_pr_url && (
                          <a
                            href={incident.github_pr_url}
                            target="_blank"
                            rel="noreferrer"
                            onClick={e => e.stopPropagation()}
                            className="text-xs font-semibold underline"
                            style={{ color: '#634F7D' }}
                          >
                            View PR →
                          </a>
                        )}
                        <span className="text-xs" style={{ color: '#003D4F44' }}>
                          {new Date(incident.created_at).toLocaleDateString('en-US', {
                            month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
                          })}
                        </span>
                      </div>
                    </div>
                  </div>
                  <span className="text-lg shrink-0" style={{ color: '#47A1AD' }}>
                    {isExpanded ? '▲' : '▼'}
                  </span>
                </button>

                {/* Expanded post-mortem */}
                {isExpanded && (
                  <div className="px-5 pb-5" style={{ borderTop: '1px solid #EDF1F3' }}>
                    <div className="pt-4 prose prose-sm max-w-none text-sm" style={{ color: '#003D4F' }}>
                      <ReactMarkdown>{incident.postmortem!}</ReactMarkdown>
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}

      {withPostmortems.length > 0 && (
        <p className="text-xs text-center" style={{ color: '#003D4F44' }}>
          {withPostmortems.length} post-mortem{withPostmortems.length !== 1 ? 's' : ''} on record
        </p>
      )}
    </div>
  )
}
